apiVersion: v1                  # API version used for defining a Service
kind: Service                   # The resource type is Service

metadata:
  name: nodejs-service          # Name of the Service

spec:
  type: NodePort                # Type of service; exposes the app on each Node's IP at a static port

  selector:
    app: nodejs                # Connect this service to pods with label app: nodejs

  ports:
    - protocol: TCP            # Protocol used (usually TCP for web apps)
      port: 80                 # Port the service is exposed on (inside the cluster)
      targetPort: 3000         # Port the container is listening on
      nodePort: 30081          # Port exposed on the node (outside the cluster); must be between 30000–32767

